server:
  shutdown: graceful

spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS:org.postgresql.Driver}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${DATASOURCE_MAX_POOL_SIZE:10}
      max-lifetime: 1740000
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/master.xml

job:
  some-job:
    enabled: ${SOME_JOB_ENABLED:false}
    cron: ${SOME_JOB_CRON}

rest:
  url:
  connectTimeout: 5000
  readTimeout: 5000
