server:
  shutdown: graceful
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS:org.postgresql.Driver}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${DATASOURCE_MAX_POOL_SIZE:10}
      max-lifetime: 1740000
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/master.xml
#    TODO почитать про эти настройки (одни для приложения, другие для пользователей приложения)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
#      client:
#        provider:
#          keycloak:
#            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
#        registration:
#          keycloak:
#            provider: keycloak
#            authorization-grant-type: client_credentials
#            client-id: ${KEYCLOAK_CLIENT_ID}
#            client-secret: ${KEYCLOAK_CLIENT_SECRET}

grpc:
  authorization.enabled: ${GRPC_SECURITY_ENABLED}
  server:
    port: ${GRPC_SERVER_PORT}
    reflection-service-enabled: true
    security:
      enabled: ${GRPC_SECURITY_ENABLED}

job:
  some-job:
    enabled: ${SOME_JOB_ENABLED:false}
    cron: ${SOME_JOB_CRON}

rest:
  url:
  connectTimeout: 5000
  readTimeout: 5000

logging:
  level:
    root: INFO

security:
  enable: ${AUTH_SECURITY_ENABLED:true}

keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  timeout:
    read: ${KEYCLOAK_CLIENT_READ_TIMEOUT:60000}
    connect: ${KEYCLOAK_CLIENT_CONNECT_TIMEOUT:15000}
  users:
    url: ${KEYCLOAK_USERS_URL}
    realm: ${KEYCLOAK_USERS_REALM}
    client-id: ${KEYCLOAK_USERS_CLIENT_ID}
    client-secret: ${KEYCLOAK_USERS_CLIENT_SECRET}